version: '3.8'
services:
  db:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: r00t
      MYSQL_USER: mrdb
      MYSQL_PASSWORD: mrdb 
      MYSQL_DATABASE: lezzo
    volumes: 
      - db-config:/etc/mysql
      - db-data:/var/lib/mysql 
    ports:
      - "3306:3306"
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "5000:5000"
volumes:
  db-config:
  db-data: